version: "2"

services:
  keycloak_db:
    image: postgres:latest
    ports:
      - "15432:15432"
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
        - POSTGRES_ROOT_PASSWORD=YOUR_POSTGRES_ROOT_PASSWORD
    volumes:
      - keycloak_postgresql:/var/lib/postgresql
      - keycloak_postgresql_data:/var/lib/postgresql/data

  keycloak:
      image: jboss/keycloak
      environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
        - POSTGRES_USER=keycloak
        - POSTGRES_DATABASE=keycloak
        - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
        - POSTGRES_PORT_5432_TCP_ADDR=postgres
        - POSTGRES_PORT_5432_TCP_PORT=5432
        - KEYCLOAK_USER=YOUR_KEYCLOAK_SUPER_USER
        - KEYCLOAK_PASSWORD=YOUR_KEYCLOAK_PASSWORD
        - PROXY_ADDRESS_FORWARDING=true
      links:
        - keycloak_db:postgres
      ports:
        - "18443:8443"
        - "18080:8080"
      volumes:
        - keycloak_data:/data

volumes: 
  keycloak_postgresql:
  keycloak_postgresql_data:
  keycloak_data:
